#!/usr/bin/env python3
"""Generate apps/console/src/lib/schema.ts from promptetheus.schema.event_schema()."""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGE_ROOT = ROOT / "packages" / "promptetheus"
sys.path.insert(0, str(PACKAGE_ROOT))

from promptetheus.schema import EVENT_TYPES, event_schema  # noqa: E402

OUT = ROOT / "apps" / "console" / "src" / "lib" / "schema.ts"


def main() -> None:
    schema = event_schema()
    event_types_literal = json.dumps(list(EVENT_TYPES))
    schema_json_literal = json.dumps(schema, indent=2)
    content = (
        "// AUTO-GENERATED by scripts/generate_schema_ts.py - do not edit by hand.\n"
        "// Source of truth: packages/promptetheus/promptetheus/schema.py (event_schema)\n\n"
        "import { z } from \"zod\";\n\n"
        f"export const EVENT_TYPES = {event_types_literal} as const;\n\n"
        "export const EventTypeSchema = z.enum(EVENT_TYPES);\n\n"
        "export const PromptetheusEventSchema = z\n"
        "  .object({\n"
        "    type: EventTypeSchema,\n"
        "    session_id: z.string().min(1),\n"
        "    timestamp: z.string(),\n"
        "    seq: z.number().int().min(0),\n"
        "    idempotency_key: z.string().min(1),\n"
        "    payload: z.record(z.unknown()),\n"
        "    metadata: z.record(z.unknown()).optional(),\n"
        "    span_id: z.string().min(1).optional(),\n"
        "    parent_id: z.string().nullable().optional(),\n"
        "  })\n"
        "  .passthrough();\n\n"
        "export const EventSchema = PromptetheusEventSchema;\n\n"
        "export type PromptetheusEvent = z.infer<typeof PromptetheusEventSchema>;\n\n"
        "export function validateEvent(event: unknown): PromptetheusEvent {\n"
        "  return PromptetheusEventSchema.parse(event);\n"
        "}\n\n"
        f"export const EVENT_SCHEMA_JSON = {schema_json_literal} as const;\n"
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
