// AUTO-GENERATED by scripts/generate_schema_ts.py - do not edit by hand.
// Source of truth: packages/promptetheus/promptetheus/schema.py (event_schema)

import { z } from "zod";

export const EVENT_TYPES = ["user_message", "agent_message", "tool_call", "tool_result", "retrieval", "browser_action", "dom_snapshot", "screenshot", "replay_artifact", "goal_check", "state_change", "session_end", "llm_call", "score", "error", "metric"] as const;

export const EventTypeSchema = z.enum(EVENT_TYPES);

export const PromptetheusEventSchema = z
  .object({
    type: EventTypeSchema,
    session_id: z.string().min(1),
    timestamp: z.string(),
    seq: z.number().int().min(0),
    idempotency_key: z.string().min(1),
    payload: z.record(z.unknown()),
    metadata: z.record(z.unknown()).optional(),
    span_id: z.string().min(1).optional(),
    parent_id: z.string().nullable().optional(),
  })
  .passthrough();

export const EventSchema = PromptetheusEventSchema;

export type PromptetheusEvent = z.infer<typeof PromptetheusEventSchema>;

export function validateEvent(event: unknown): PromptetheusEvent {
  return PromptetheusEventSchema.parse(event);
}

export const EVENT_SCHEMA_JSON = {
  "title": "PromptetheusEvent",
  "type": "object",
  "required": [
    "type",
    "session_id",
    "timestamp",
    "seq",
    "idempotency_key",
    "payload"
  ],
  "additionalProperties": true,
  "properties": {
    "type": {
      "type": "string",
      "enum": [
        "user_message",
        "agent_message",
        "tool_call",
        "tool_result",
        "retrieval",
        "browser_action",
        "dom_snapshot",
        "screenshot",
        "replay_artifact",
        "goal_check",
        "state_change",
        "session_end",
        "llm_call",
        "score",
        "error",
        "metric"
      ]
    },
    "session_id": {
      "type": "string",
      "minLength": 1
    },
    "timestamp": {
      "type": "string"
    },
    "seq": {
      "type": "integer",
      "minimum": 0
    },
    "idempotency_key": {
      "type": "string",
      "minLength": 1
    },
    "payload": {
      "type": "object"
    },
    "metadata": {
      "type": "object"
    },
    "span_id": {
      "type": "string",
      "minLength": 1
    },
    "parent_id": {
      "type": [
        "string",
        "null"
      ]
    }
  },
  "definitions": {
    "voice_message_metadata": {
      "type": "object",
      "properties": {
        "channel": {
          "type": "string",
          "enum": [
            "voice"
          ]
        },
        "speaker": {
          "type": "string",
          "enum": [
            "user",
            "agent"
          ]
        },
        "start_ms": {
          "type": "integer",
          "minimum": 0
        },
        "end_ms": {
          "type": "integer",
          "minimum": 0
        },
        "interrupted": {
          "type": "boolean"
        },
        "sentiment": {
          "type": "number",
          "minimum": -1,
          "maximum": 1
        }
      }
    }
  },
  "events": {
    "user_message": {
      "properties": {
        "content": {
          "type": "string"
        },
        "metadata": {
          "$ref": "#/definitions/voice_message_metadata"
        }
      }
    },
    "agent_message": {
      "properties": {
        "content": {
          "type": "string"
        },
        "metadata": {
          "$ref": "#/definitions/voice_message_metadata"
        }
      }
    },
    "tool_call": {
      "properties": {
        "tool_name": {
          "type": "string"
        },
        "arguments": {
          "type": "object"
        },
        "call_id": {
          "type": "string"
        },
        "metadata": {
          "type": "object"
        }
      }
    },
    "tool_result": {
      "properties": {
        "call_id": {
          "type": "string"
        },
        "result": {},
        "error": {
          "type": "string"
        },
        "metadata": {
          "type": "object"
        }
      }
    },
    "retrieval": {
      "properties": {
        "query": {
          "type": "string"
        },
        "documents": {
          "type": "array"
        },
        "metadata": {
          "type": "object"
        }
      }
    },
    "browser_action": {
      "properties": {
        "action": {
          "type": "string"
        },
        "target": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "metadata": {
          "type": "object"
        }
      }
    },
    "dom_snapshot": {
      "properties": {
        "url": {
          "type": "string"
        },
        "visible_text": {
          "type": "string"
        },
        "selected_values": {
          "type": "object"
        },
        "warnings": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "metadata": {
          "type": "object"
        }
      }
    },
    "screenshot": {
      "properties": {
        "artifact_id": {
          "type": "string"
        },
        "storage_path": {
          "type": "string"
        },
        "size_bytes": {
          "type": "integer",
          "minimum": 0
        },
        "source_type": {
          "type": "string",
          "enum": [
            "bytes",
            "path"
          ]
        },
        "metadata": {
          "type": "object"
        }
      }
    },
    "replay_artifact": {
      "properties": {
        "artifact_id": {
          "type": "string"
        },
        "artifact_type": {
          "type": "string",
          "enum": [
            "screen_recording",
            "audio_recording"
          ]
        },
        "storage_path": {
          "type": "string"
        },
        "started_at": {
          "type": "string"
        },
        "ended_at": {
          "type": "string"
        },
        "duration_ms": {
          "type": "integer"
        },
        "event_time_map": {
          "type": "object",
          "additionalProperties": {
            "type": "integer"
          }
        },
        "metadata": {
          "type": "object"
        }
      }
    },
    "goal_check": {
      "properties": {
        "passed": {
          "type": "boolean"
        },
        "mismatches": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "metadata": {
          "type": "object"
        }
      }
    },
    "state_change": {
      "properties": {
        "name": {
          "type": "string"
        },
        "before": {},
        "after": {},
        "span_name": {
          "type": "string"
        },
        "duration_ms": {
          "type": "integer",
          "minimum": 0
        },
        "metadata": {
          "type": "object"
        }
      }
    },
    "session_end": {
      "properties": {
        "status": {
          "type": "string"
        },
        "error": {
          "type": "string"
        },
        "metadata": {
          "type": "object"
        }
      }
    },
    "llm_call": {
      "reserved": true,
      "properties": {
        "model": {
          "type": "string"
        },
        "prompt_ref": {
          "type": "string"
        },
        "messages_ref": {
          "type": "string"
        },
        "input_tokens": {
          "type": "integer"
        },
        "output_tokens": {
          "type": "integer"
        },
        "latency_ms": {
          "type": "integer"
        },
        "metadata": {
          "type": "object"
        }
      }
    },
    "score": {
      "properties": {
        "name": {
          "type": "string"
        },
        "value": {
          "type": [
            "number",
            "boolean"
          ]
        },
        "comment": {
          "type": "string"
        },
        "source": {
          "type": "string"
        },
        "metadata": {
          "type": "object"
        }
      }
    },
    "error": {
      "properties": {
        "message": {
          "type": "string"
        },
        "error_type": {
          "type": "string"
        },
        "traceback": {
          "type": "string"
        },
        "handled": {
          "type": "boolean"
        },
        "metadata": {
          "type": "object"
        }
      }
    },
    "metric": {
      "properties": {
        "name": {
          "type": "string"
        },
        "value": {
          "type": "number"
        },
        "unit": {
          "type": "string"
        },
        "metadata": {
          "type": "object"
        }
      }
    }
  }
} as const;
